### PR TITLE
Escape JavaScript parameters 

### PR DESCRIPTION
**Pull request by hpique**
Only considering "\" and "'" so far. There might be other characters that also need to be escaped.

While we only had problems with the `label` parameter (as it is sometimes user-generated), I think it's best to sanitise all of them just in case a developer forgets that these values will be used between JavaScript single-quotes.

Not heavily tested.

### CODE REVIEW

**Comment by Daij-Djan** [comment]
your reasoning is sound and this functionality makes total sense.. but..
can't we use the framework's CFStringEscape boa bulb function?

**Comment by hpique** [comment]
Can't find CFStringEscape in the docs. Is it from a third-party framework?

**Comment by Daij-Djan** [comment]
Hey sorry I got the name wrong. stupid CF naming ^^ ;)
its CFXMLCreateStringByEscapingEntities

that can escape what you specifiy in a dict.
or you pass in NULL and it escapes the default: < > ? " & '
using the predefined html entities 

--- :(( likely that isnt as nice though ... 
and not whats needed here .. 

sorry again. I just got it: we need to sanitize it for javascript; not for html. :/

**Comment by hpique** [comment]
Yep, that's why I'm doing it manually. Also, we need to escape either double quotes or single quotes but not both.

**Comment by Daij-Djan** [comment]
yep I was a bit thick 
looks good :thumbsup:

**Pull request merged**
